import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menus from "../components/Menus";
import Footer from "../components/Footer";
import TransitionWrapper from "@/components/TransitionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Menus />
        {/* <TransitionWrapper /> */}
        <div className="pt-20">{children}</div>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
